version: "3"
services:
  postgres:
    image: postgres:14.5
    container_name: daikon_project_db_dev
    environment:
      - POSTGRES_USER=tpt_user
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - TZ='GMT+0'
      - PGTZ='GMT+0'
    ports:
      - "40000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - daikon-ce-network

  api-backend:
    container_name: daikon_core_server_ce_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5005:5005
    volumes:
      - /app/API/bin
      - /app/Infrastructure/bin
      - /app/Application/bin
      - /app/Domain/bin
      - /app/Persistence/bin
      - /app/DataView/bin
      - /app/Adapter/bin
      - /app/API/obj
      - /app/Infrastructure/obj
      - /app/Application/obj
      - /app/Domain/obj
      - /app/Persistence/obj
      - /app/DataView/obj
      - /app/Adapter/obj
      - ./AppData:/AppData
      - ./:/app
    environment:
      - AZURE_VALID_AUDIENCE=${AZURE_VALID_AUDIENCE}
      - SSO_AUTHORITY=${SSO_AUTHORITY}
      - LOCAL_TOKENKEY=${LOCAL_TOKENKEY}
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
      - PGSQL_CONNECTION_STRING=${PGSQL_CONNECTION_STRING}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - TZ='GMT+0'
      - PGTZ='GMT+0'
    networks:
      - daikon-ce-network
  
  # keycloak:
  #   image: jboss/keycloak
  #   env_file: ./keycloak.env
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - daikon-ce-network
  #   ports:
  #     - 8080:8080

  # keycloak-db:
  #   env_file: ./keycloak.env
  #   image: postgres:10.1
  #   volumes:
  #     - ./keycloak-db-pg:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - daikon-ce-network

networks:
  daikon-ce-network:
    driver: bridge