version: "3"
services:
  api-backend:
    container_name: daikon_core_server_ce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - /app/API/bin
      - /app/Infrastructure/bin
      - /app/Application/bin
      - /app/Domain/bin
      - /app/Persistence/bin
      - /app/DataView/bin
      - /app/Adapter/bin
      - /app/API/obj
      - /app/Infrastructure/obj
      - /app/Application/obj
      - /app/Domain/obj
      - /app/Persistence/obj
      - /app/DataView/obj
      - /app/Adapter/obj
      - ./AppData:/AppData
      - ./:/app

    environment:
      - AZURE_VALID_AUDIENCE=${AZURE_VALID_AUDIENCE}
      - SSO_AUTHORITY=${SSO_AUTHORITY}
      - LOCAL_TOKENKEY=${LOCAL_TOKENKEY}
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Production
      - PGSQL_CONNECTION_STRING=${PGSQL_CONNECTION_STRING}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
