version: "3"
services:
  postgres:
    image: postgres:14.5
    container_name: project_db
    environment:
      - POSTGRES_USER=tpt_user
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "40000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api-backend:
    container_name: daikon_core_server_dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - 5005:5005
    volumes:
      - /app/API/bin
      - /app/Infrastructure/bin
      - /app/Application/bin
      - /app/Domain/bin
      - /app/Persistence/bin
      - /app/DataView/bin
      - /app/API/obj
      - /app/Infrastructure/obj
      - /app/Application/obj
      - /app/Domain/obj
      - /app/Persistence/obj
      - /app/DataView/obj
      - ./:/app
    environment:
      - AZURE_VAILD_AUDIENCE=${AZURE_VAILD_AUDIENCE}
      - AZURE_AUTHORITY=${AZURE_AUTHORITY}
      - LOCAL_TOKENKEY=${LOCAL_TOKENKEY}
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
      - PGSQL_CONNECTION_STRING=${PGSQL_CONNECTION_STRING}
      - PGPGUSER=${PGPGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
