version: "3"
services:
  postgres:
    image: postgres:10.5
    container_name: project_db
    restart: always
    environment:
      - POSTGRES_USER=tpt_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "40000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api-backend:
    container_name: project_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - "postgres"
    ports:
      - 5000:5000
    volumes:
      - /app/API/bin
      - /app/Infrastructure/bin
      - /app/Application/bin
      - /app/Domain/bin
      - /app/Persistence/bin
      - /app/API/obj
      - /app/Infrastructure/obj
      - /app/Application/obj
      - /app/Domain/obj
      - /app/Persistence/obj
      - ./:/app
    environment:
      - AZURE_VAILD_AUDIENCE=${AZURE_VAILD_AUDIENCE}
      - AZURE_AUTHORITY=${AZURE_AUTHORITY}
      - LOCAL_TOKENKEY=${LOCAL_TOKENKEY}
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
